github.com:
    users:
        hugo-berendi:
            oauth_token: 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
    git_protocol: https
    oauth_token: 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
    user: hugo-berendi
