github.com:
    users:
        hugo-berendi:
            oauth_token: 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
    git_protocol: https
    user: hugo-berendi
    oauth_token: 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
